### PR TITLE
Fix `<Menu/>` check if button exists

### LINKED ISSUE #52: 🐛  `<Menu>` focus button after close items
Clicking outside the menu items should close menu, and focus button.

[Test](https://github.com/GavinJoyce/ember-headlessui/blob/master/tests/integration/components/menu-test.js#L539)

[Code](https://github.com/GavinJoyce/ember-headlessui/blob/master/addon/components/menu.js#L36)

Bug:

### **Steps to reproduce the problem**

* menu is rendered on the dialog, 
* clicking outside dialog (close dialog and menu)

### **What went wrong?**

* Button doesn't exist and cannot be focused.

Captura de pantalla 2021-06-15 a las 9 52 05

https://user-images.githubusercontent.com/11621383/122016204-1e8ef680-cdc1-11eb-979e-238beedb3c8a.mov

### **What is the expected behavior?**

Does not focus anything ?

### PR DESCRIPTION
**Pull request by far-fetched**
Fixes #52

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Thanks for this @far-fetched. What do you think about adding a test?

**Comment by far-fetched** [comment]
I wasn't sure that brings any value. But if you think that, I can do it.

File: addon/components/menu.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default class Menu extends Component {
     if (this.isOpen) {
       this.isOpen = false;
       next(() => {
-        document.getElementById(this.buttonGuid).focus();
+        document.getElementById(this.buttonGuid)?.focus();
```
Comment (achambers) [inline addon/components/menu.js:36]: I'm always a little confused about Babel, but does the optional chaining used here require the consuming app to have the Babel plugin (https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining.html) installed?

Is there any chance this could cause grief to app's who's users don't use a browser that yet supports optional chaining (https://caniuse.com/mdn-javascript_operators_optional_chaining) ?

Should we just go the long hard form here to be safe?

/cc @far-fetched @GavinJoyce

Comment (far-fetched) [reply addon/components/menu.js:36]: I think it will break with old versions. I guess the question is how far we want to go with browser support.

Comment (achambers) [reply addon/components/menu.js:36]: I think where this case is concerned, my preference is to go with old school `if`. Can’t see a lot to be gained using optional chaining here.

**Review by achambers — APPROVED** [review]
Thanks @far-fetched

**Comment by achambers** [comment]
Actually, before I merge this @far-fetched , will you please rebase and squash the commits together. Both 9415928a61fc8c4a0542d08e9b6d73365b245edb and 9415928a61fc8c4a0542d08e9b6d73365b245edb are unnecessary in "telling the story" of this change.

**Comment by far-fetched** [comment]
🚀

**Comment by achambers** [comment]
Thanks @far-fetched . Released as https://github.com/GavinJoyce/ember-headlessui/releases/tag/v0.4.1
